# Generated by Django 4.1.4 on 2022-12-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_machine', models.TextField(unique=True, verbose_name='Зав. № машины')),
                ('technique_model', models.TextField(verbose_name='Модель техники')),
                ('engine_model', models.TextField(verbose_name='Модель двигателя')),
                ('engine_number', models.TextField(verbose_name='Зав. № двигателя')),
                ('transmission_model', models.TextField(verbose_name='Модель трансмиссии')),
                ('transmission_number', models.TextField(verbose_name='Зав. № трансмиссии')),
                ('drive_axle_model', models.TextField(verbose_name='Модель ведущего моста')),
                ('drive_axle_number', models.TextField(verbose_name='Зав. № ведущего моста')),
                ('steering_bridge_model', models.TextField(verbose_name='Модель управляемоо моста')),
                ('steering_bridge_number', models.TextField(verbose_name='Зав. № управляемоо моста')),
                ('supply_contract', models.TextField(verbose_name='Договор поставки №, дата')),
                ('shipping_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.TextField(verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client', models.TextField(verbose_name='Клиент')),
                ('service_company', models.TextField(verbose_name='сервисная компания')),
            ],
        ),
    ]
