# Generated by Django 4.1.4 on 2022-12-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
            },
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Характер отказа',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_machine', models.TextField(unique=True, verbose_name='Зав. № машины')),
                ('engine_number', models.TextField(verbose_name='Зав. № двигателя')),
                ('transmission_number', models.TextField(verbose_name='Зав. № трансмиссии')),
                ('drive_axle_number', models.TextField(verbose_name='Зав. № ведущего моста')),
                ('steering_bridge_number', models.TextField(verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.TextField(verbose_name='Договор поставки №, дата')),
                ('shipping_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.TextField(verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client', models.TextField(verbose_name='Клиент')),
                ('drive_axle_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.driveaxlemodel', verbose_name='Модель ведущего моста')),
                ('engine_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.enginemodel', verbose_name='Модель двигателя')),
            ],
            options={
                'verbose_name': 'Машина',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
            },
        ),
        migrations.CreateModel(
            name='SteeringBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='TechniqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.FloatField(verbose_name='Наработка, м/час')),
                ('work_order_number', models.TextField(verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='дата заказ-наряда')),
                ('company_make_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany')),
                ('machine_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.machine')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicetype', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': '«ТО» (техническое обслуживание)',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='machine',
            name='steering_bridge_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.steeringbridgemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='technique_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.techniquemodel', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejection', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.FloatField(verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('failure_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.failurenode', verbose_name='Узел отказа')),
                ('machine_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.machine')),
                ('recovery_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.recoverymethod', verbose_name='Способ восстановления')),
                ('service_company_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламации',
            },
        ),
    ]
