# Generated by Django 4.1.4 on 2022-12-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Машина'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.TextField(verbose_name='Сервисная компания'),
        ),
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.TextField(verbose_name='Вид ТО')),
                ('service_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.FloatField(verbose_name='Наработка, м/час')),
                ('work_order_number', models.TextField(verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='дата заказ-наряда')),
                ('company_make_service', models.TextField(verbose_name='Организация, проводившая ТО')),
                ('machine_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.machine')),
            ],
            options={
                'verbose_name': '«ТО» (техническое обслуживание)',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejection', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.FloatField(verbose_name='Наработка, м/час')),
                ('failure_node', models.TextField(verbose_name='Узел отказа')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('recovery_method', models.TextField(verbose_name='Способ восстановления')),
                ('spare_parts', models.TextField(verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('machine_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.machine')),
            ],
            options={
                'verbose_name': '«ТО» (техническое обслуживание)',
            },
        ),
    ]
