# Generated by Django 4.1.4 on 2022-12-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='technique_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.techniquemodel', verbose_name='Модель техники'),
        ),
    ]
