# Generated by Django 4.1.4 on 2022-12-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_machine_technique_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoverymethod',
            options={'verbose_name': 'Способ восстановления'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.failurenode', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.driveaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_bridge_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.steeringbridgemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='to',
            name='service_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.servicetype', verbose_name='Вид ТО'),
        ),
    ]
