# Generated by Django 4.1.4 on 2022-12-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_complaint_spare_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='spare_parts',
            field=models.TextField(blank=True, null=True, verbose_name='Используемые запасные части'),
        ),
    ]
